import { requireComfyRoot } from "./local_paths.cjs";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..");
const liveRoot = path.join(requireComfyRoot(), "user", "default", "workflows", "Codex MCP Demos");
const workflowName = "10E H3 Thin Controls Lab.json";
const expectedGoldSha256 = "2cd91cfbe51f3d5bd66f43cb2d34417894d18ad46b18ae0360a24b672013d037";
const repoWorkflowRoot = path.join(repoRoot, "workflows", "Codex MCP Demos");
const goldPath = path.join(
  repoWorkflowRoot,
  "10 GOLD STANDARD - MiniMax H3 Long Form Shot Builder.json",
);
const repoWorkflowPath = path.join(repoWorkflowRoot, workflowName);
const liveWorkflowPath = path.join(liveRoot, workflowName);
const apiPath = path.join(repoRoot, "tests", "h3_m4_thin_controls_smoke_api.json");

function sha256(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}

const goldHash = sha256(fs.readFileSync(goldPath));
if (goldHash !== expectedGoldSha256) {
  throw new Error(
    `Protected Gold changed: expected ${expectedGoldSha256}, found ${goldHash}`,
  );
}

function input(name, type, link = null, widget = true) {
  return {
    name,
    type,
    link,
    ...(widget ? { widget: { name } } : {}),
  };
}

function output(name, type, links = []) {
  return { name, type, links };
}

const shotPlan = [
  {
    shot_id: "S01",
    title: "The arrival",
    scene: "Kitchen",
    action: "A goat walks to the table and stops beside the teapot.",
    camera: "Locked medium-wide shot at goat eye level.",
    dialogue: "Mabel says, \"Tea — now?\"",
    references: ["input/H3_Long_Form_Test_Start.png", "prop:blue-teapot"],
    profile_override: "Gold Base",
    handoff_notes: "Keep the goat on frame left.",
  },
  {
    shot_id: "S02",
    title: "The answer",
    scene: "Kitchen",
    action: "Arthur turns from the sink without moving the teapot.",
    camera: "Slow push-in while preserving the screen direction.",
    dialogue: "Arthur replies, \"Only if it is Earl Grey.\"",
    references: ["input/H3_Long_Form_Test_Start.png", "prop:blue-teapot"],
    profile_override: "Gold Base",
    handoff_notes: "Preserve the teapot position from S01.",
  },
  {
    shot_id: "S03",
    title: "The decision",
    scene: "Kitchen",
    action: "Mabel nudges the teapot toward Arthur and waits.",
    camera: "Return to the locked medium-wide composition.",
    dialogue: "Mabel says, \"Deal.\"",
    references: ["input/H3_Long_Form_Test_Start.png", "prop:blue-teapot"],
    profile_override: "Gold Base",
    handoff_notes: "End with a clean continuation frame.",
  },
];
const shotPlanJson = JSON.stringify(shotPlan);
const engine = "m4-state-lab-no-render";

const workflow = {
  id: "10e00000-0000-4000-8000-000000000004",
  revision: 0,
  last_node_id: 16,
  last_link_id: 27,
  nodes: [
    {
      id: 1,
      type: "PixaromaNote",
      pos: [20, 20],
      size: [3060, 250],
      flags: {},
      order: 0,
      mode: 0,
      inputs: [input("note_json", "STRING")],
      outputs: [],
      title: "START HERE — THIN CONTROLS WITHOUT A GENERATION",
      properties: { "Node name for S&R": "PixaromaNote" },
      widgets_values: [
        JSON.stringify({
          version: 1,
          content: "<h2>M4 THIN CONTROLS LAB</h2><ol><li>Select the evidence-cleared Gold Base or Quick Preview recipe. Turbo is intentionally absent because its comparison is not yet recorded.</li><li>Edit the JSON plan only with an explicit reset. Each queued execution reads the current shot at execution time.</li><li>Run once per shot. A matching recorded take commits accepted work and advances the plan; rejected work stays on the same shot.</li></ol><p>This lab loads one known-good frame to exercise project state and provenance. It contains no model, sampler, generation, partner node, or paid route. Gold is not connected.</p>",
          buttonColor: "#f66744",
          lineColor: "#f66744",
          width: 3060,
          height: 220,
          backgroundColor: "#2a2a2a",
        }),
        "",
      ],
      color: "#1d1d1d",
      bgcolor: "#2a2a2a",
    },
    {
      id: 2,
      type: "CodexH3RenderProfileControl",
      pos: [40, 340],
      size: [500, 310],
      flags: {},
      order: 1,
      mode: 0,
      inputs: [input("profile", "COMBO"), input("engine", "STRING")],
      outputs: [
        output("profile_token", "H3_RENDER_PROFILE", [1]),
        output("profile_name", "STRING", [2]),
        output("steps", "INT"),
        output("cfg", "FLOAT"),
        output("sampler_name", "STRING"),
        output("scheduler", "STRING"),
        output("required_lora", "STRING"),
        output("status", "STRING", [3]),
      ],
      title: "1. RENDER PROFILE — evidence-cleared recipe only",
      properties: { "Node name for S&R": "CodexH3RenderProfileControl" },
      widgets_values: ["Gold Base", engine],
      color: "#6A4C93",
      bgcolor: "#2a2a2a",
    },
    {
      id: 3,
      type: "CodexH3ShotPlanControl",
      pos: [40, 760],
      size: [740, 650],
      flags: {},
      order: 2,
      mode: 0,
      inputs: [
        input("project", "STRING"),
        input("branch", "STRING"),
        input("plan_name", "STRING"),
        input("plan_json", "STRING"),
        input("action", "COMBO"),
      ],
      outputs: [
        output("plan_control", "H3_SHOT_PLAN_CONTROL", [4]),
        output("status", "STRING", [5]),
        output("position", "STRING"),
        output("plan_sha256", "STRING"),
      ],
      title: "2. SHOT PLAN — versioned JSON and explicit navigation",
      properties: { "Node name for S&R": "CodexH3ShotPlanControl" },
      widgets_values: [
        "H3 M4 Thin Controls Lab",
        "main",
        "Kitchen sequence",
        shotPlanJson,
        "ensure",
      ],
      color: "#355C7D",
      bgcolor: "#2a2a2a",
    },
    {
      id: 4,
      type: "CodexH3ShotPlanReader",
      pos: [900, 760],
      size: [520, 420],
      flags: {},
      order: 3,
      mode: 0,
      inputs: [input("plan_control", "H3_SHOT_PLAN_CONTROL", 4, false)],
      outputs: [
        output("shot_token", "H3_SHOT_TOKEN", [6]),
        output("project", "STRING", [7]),
        output("scene", "STRING", [8]),
        output("shot", "STRING", [9]),
        output("branch", "STRING", [10]),
        output("prompt", "STRING", [11]),
        output("exact_dialogue", "STRING"),
        output("references_json", "STRING", [12]),
        output("profile_override", "STRING"),
        output("handoff_notes", "STRING"),
        output("status", "STRING", [13]),
      ],
      title: "3. CURRENT SHOT — read at execution time",
      properties: { "Node name for S&R": "CodexH3ShotPlanReader" },
      widgets_values: [],
      color: "#355C7D",
      bgcolor: "#2a2a2a",
    },
    {
      id: 5,
      type: "LoadImage",
      pos: [900, 340],
      size: [500, 350],
      flags: {},
      order: 4,
      mode: 0,
      inputs: [input("image", "COMBO")],
      outputs: [output("IMAGE", "IMAGE", [14]), output("MASK", "MASK")],
      title: "KNOWN-GOOD FRAME — state exercise only",
      properties: { "Node name for S&R": "LoadImage", cnr_id: "comfy-core" },
      widgets_values: ["H3_Long_Form_Test_Start.png", "image"],
      color: "#B45574",
      bgcolor: "#2a2a2a",
    },
    {
      id: 6,
      type: "CodexH3ProjectControl",
      pos: [1500, 340],
      size: [720, 850],
      flags: {},
      order: 5,
      mode: 0,
      inputs: [
        input("project", "STRING", 7, false),
        input("scene", "STRING", 8, false),
        input("shot", "STRING", 9, false),
        input("branch", "STRING", 10, false),
        input("engine", "STRING"),
        input("model", "STRING"),
        input("lora", "STRING"),
        input("profile", "STRING", 2, false),
        input("prompt", "STRING", 11, false),
        input("references_json", "STRING", 12, false),
        input("parent_handoff", "STRING"),
        input("native_width", "INT"),
        input("native_height", "INT"),
        input("delivery_width", "INT"),
        input("delivery_height", "INT"),
        input("seed", "INT"),
        input("render_profile", "H3_RENDER_PROFILE", 1, false),
      ],
      outputs: [
        output("take_token", "H3_PROJECT_TAKE", [15, 16]),
        output("take_label", "STRING"),
        output("render_seed", "INT"),
        output("status", "STRING", [17]),
      ],
      title: "4. PROJECT TAKE — profile and shot provenance",
      properties: { "Node name for S&R": "CodexH3ProjectControl" },
      widgets_values: [
        "H3 M4 Thin Controls Lab",
        "Kitchen",
        "S01 The arrival",
        "main",
        engine,
        "(no model loaded)",
        "(none)",
        "Gold Base",
        "Execution-time shot prompt is linked from the plan reader.",
        "[]",
        "",
        864,
        480,
        864,
        480,
        42,
      ],
      color: "#355C7D",
      bgcolor: "#2a2a2a",
    },
    {
      id: 7,
      type: "CodexH3SafeContinuationStore",
      pos: [2300, 340],
      size: [600, 360],
      flags: {},
      order: 6,
      mode: 0,
      inputs: [
        input("images", "IMAGE", 14, false),
        input("token", "H3_PROJECT_TAKE", 15, false),
        input("mode", "COMBO"),
        input("expected_width", "INT"),
        input("expected_height", "INT"),
        input("continuity_warning", "STRING"),
      ],
      outputs: [
        output("handoff_frame", "IMAGE", [18]),
        output("status", "STRING", [19]),
        output("accepted", "BOOLEAN", [20, 22]),
        output("handoff_path", "STRING", [21, 23]),
        output("gate_record_json", "STRING"),
      ],
      title: "5. TECHNICAL GATE — accepted or retained",
      properties: { "Node name for S&R": "CodexH3SafeContinuationStore" },
      widgets_values: ["BLOCK TECHNICAL", 864, 480, ""],
      color: "#f66744",
      bgcolor: "#2a2a2a",
    },
    {
      id: 8,
      type: "CodexH3TakeRecorder",
      pos: [2300, 790],
      size: [600, 390],
      flags: {},
      order: 7,
      mode: 0,
      inputs: [
        input("token", "H3_PROJECT_TAKE", 16, false),
        input("take_state", "COMBO"),
        input("output_paths", "STRING", 21, false),
        input("completion_signal", "STRING", 19, false),
        input("accepted_signal", "BOOLEAN", 20, false),
      ],
      outputs: [
        output("status", "STRING", [26]),
        output("take_record_json", "STRING", [24]),
        output("take_manifest_path", "STRING"),
        output("project_index_path", "STRING"),
      ],
      title: "6. TAKE RECORD — immutable evidence before commit",
      properties: { "Node name for S&R": "CodexH3TakeRecorder" },
      widgets_values: ["auto"],
      color: "#2E7D32",
      bgcolor: "#2a2a2a",
    },
    {
      id: 9,
      type: "CodexH3ShotPlanCommit",
      pos: [2300, 1260],
      size: [600, 300],
      flags: {},
      order: 8,
      mode: 0,
      inputs: [
        input("shot_token", "H3_SHOT_TOKEN", 6, false),
        input("accepted", "BOOLEAN", 22, false),
        input("handoff_path", "STRING", 23, false),
        input("take_record_json", "STRING", 24, false),
      ],
      outputs: [
        output("status", "STRING", [27]),
        output("position", "STRING"),
        output("plan_complete", "BOOLEAN"),
      ],
      title: "7. PLAN COMMIT — advance accepted current take only",
      properties: { "Node name for S&R": "CodexH3ShotPlanCommit" },
      widgets_values: [],
      color: "#2E7D32",
      bgcolor: "#2a2a2a",
    },
    {
      id: 10,
      type: "PreviewImage",
      pos: [2980, 340],
      size: [400, 520],
      flags: {},
      order: 9,
      mode: 0,
      inputs: [input("images", "IMAGE", 18, false)],
      outputs: [],
      title: "INSPECTED HANDOFF — preview only",
      properties: { "Node name for S&R": "PreviewImage", cnr_id: "comfy-core" },
      widgets_values: [],
      color: "#2E7D32",
      bgcolor: "#2a2a2a",
    },
    ...[
      [11, [40, 1480], "PROFILE STATUS", 3],
      [12, [620, 1480], "PLAN STATUS", 5],
      [13, [1200, 1480], "SHOT STATUS", 13],
      [14, [1780, 1480], "TAKE STATUS", 17],
      [15, [2940, 1260], "PLAN COMMIT STATUS", 27],
      [16, [2940, 940], "TAKE RECORD STATUS", 26],
    ].map(([id, pos, title, link], index) => ({
      id,
      type: "PixaromaShowText",
      pos,
      size: [520, 230],
      flags: {},
      order: 10 + index,
      mode: 0,
      inputs: [input("source", "*", link, false)],
      outputs: [output("text", "STRING")],
      title,
      properties: { "Node name for S&R": "PixaromaShowText" },
      widgets_values: [""],
      color: index < 3 ? "#355C7D" : "#2E7D32",
      bgcolor: "#2a2a2a",
    })),
  ],
  links: [
    [1, 2, 0, 6, 16, "H3_RENDER_PROFILE"],
    [2, 2, 1, 6, 7, "STRING"],
    [3, 2, 7, 11, 0, "*"],
    [4, 3, 0, 4, 0, "H3_SHOT_PLAN_CONTROL"],
    [5, 3, 1, 12, 0, "*"],
    [6, 4, 0, 9, 0, "H3_SHOT_TOKEN"],
    [7, 4, 1, 6, 0, "STRING"],
    [8, 4, 2, 6, 1, "STRING"],
    [9, 4, 3, 6, 2, "STRING"],
    [10, 4, 4, 6, 3, "STRING"],
    [11, 4, 5, 6, 8, "STRING"],
    [12, 4, 7, 6, 9, "STRING"],
    [13, 4, 10, 13, 0, "*"],
    [14, 5, 0, 7, 0, "IMAGE"],
    [15, 6, 0, 7, 1, "H3_PROJECT_TAKE"],
    [16, 6, 0, 8, 0, "H3_PROJECT_TAKE"],
    [17, 6, 3, 14, 0, "*"],
    [18, 7, 0, 10, 0, "IMAGE"],
    [19, 7, 1, 8, 3, "STRING"],
    [20, 7, 2, 8, 4, "BOOLEAN"],
    [21, 7, 3, 8, 2, "STRING"],
    [22, 7, 2, 9, 1, "BOOLEAN"],
    [23, 7, 3, 9, 2, "STRING"],
    [24, 8, 1, 9, 3, "STRING"],
    [26, 8, 0, 16, 0, "*"],
    [27, 9, 0, 15, 0, "*"],
  ],
  groups: [
    { title: "1 — EVIDENCE-CLEARED PROFILE", bounding: [20, 300, 760, 390], color: "#6A4C93", font_size: 22 },
    { title: "2 — VERSIONED EXECUTION PLAN", bounding: [20, 720, 1420, 720], color: "#355C7D", font_size: 22 },
    { title: "3 — PROJECT PROVENANCE", bounding: [1480, 300, 760, 930], color: "#355C7D", font_size: 22 },
    { title: "4 — ACCEPTANCE AND COMMIT", bounding: [2280, 300, 1140, 1300], color: "#2E7D32", font_size: 22 },
    { title: "5 — OPERATOR STATUS", bounding: [20, 1440, 3400, 310], color: "#f66744", font_size: 22 },
  ],
  config: {},
  extra: { ds: { scale: 0.58, offset: [40, 40] } },
  version: 0.4,
};

const apiGraph = {
  "1": {
    class_type: "CodexH3RenderProfileControl",
    inputs: { profile: "Gold Base", engine },
  },
  "2": {
    class_type: "CodexH3ShotPlanControl",
    inputs: {
      project: "H3 M4 Live Validation 2026-08-25",
      branch: "main",
      plan_name: "Kitchen sequence",
      plan_json: shotPlanJson,
      action: "ensure",
    },
  },
  "3": {
    class_type: "CodexH3ShotPlanReader",
    inputs: { plan_control: ["2", 0] },
  },
  "4": {
    class_type: "LoadImage",
    inputs: { image: "H3_Long_Form_Test_Start.png" },
  },
  "5": {
    class_type: "CodexH3ProjectControl",
    inputs: {
      project: ["3", 1],
      scene: ["3", 2],
      shot: ["3", 3],
      branch: ["3", 4],
      engine,
      model: "(no model loaded)",
      lora: "(none)",
      profile: ["1", 1],
      prompt: ["3", 5],
      references_json: ["3", 7],
      parent_handoff: "",
      native_width: 864,
      native_height: 480,
      delivery_width: 864,
      delivery_height: 480,
      seed: 42,
      render_profile: ["1", 0],
    },
  },
  "6": {
    class_type: "CodexH3SafeContinuationStore",
    inputs: {
      images: ["4", 0],
      token: ["5", 0],
      mode: "BLOCK TECHNICAL",
      expected_width: 864,
      expected_height: 480,
      continuity_warning: "",
    },
  },
  "7": {
    class_type: "CodexH3TakeRecorder",
    inputs: {
      token: ["5", 0],
      take_state: "auto",
      output_paths: ["6", 3],
      completion_signal: ["6", 1],
      accepted_signal: ["6", 2],
    },
  },
  "8": {
    class_type: "CodexH3ShotPlanCommit",
    inputs: {
      shot_token: ["3", 0],
      accepted: ["6", 2],
      handoff_path: ["6", 3],
      take_record_json: ["7", 1],
    },
  },
  "9": { class_type: "PreviewImage", inputs: { images: ["6", 0] } },
};

for (const outputPath of [repoWorkflowPath, liveWorkflowPath]) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `${JSON.stringify(workflow, null, 2)}\n`);
  console.log(outputPath);
}
fs.writeFileSync(apiPath, `${JSON.stringify(apiGraph, null, 2)}\n`);
console.log(apiPath);
console.log(`10E SHA-256: ${sha256(fs.readFileSync(repoWorkflowPath))}`);
console.log(`Gold SHA-256: ${goldHash}`);
