const { requireComfyRoot } = require("./local_paths.cjs");
const fs = require("fs");
const path = require("path");

const comfy = requireComfyRoot();
const settingsUrl = "http://127.0.0.1:8188/settings/Pixaroma.Prompt.Library";
const settingFile = path.join(comfy, "user", "default", "comfy.settings.json");
const workspace = path.resolve(__dirname, "..", "tag-library");
const exportPath = path.join(workspace, "pixaroma-tag-library-with-entity-mix.json");
const backupDir = path.join(workspace, "backups");

const lists = {
  CodexPoseableCharacters: {
    subject_everyday_human: [
      "Nora Pell, a compact middle-aged bicycle mechanic with cropped silver hair, strong forearms, a navy work shirt, patched canvas trousers and a tiny enamel wheel badge",
      "Malik Rowan, a tall young community gardener with warm brown skin, short twists, a faded green overshirt, mud-marked boots and a packet of sunflower seeds",
      "Eileen Moss, an elderly coastal cartographer with wind-reddened cheeks, a white bob, a mustard raincoat, wool trousers and a brass folding ruler",
      "Tomas Venn, a broad-shouldered night baker with flour on his dark curls, rolled white sleeves, checked trousers and a small wooden bread stamp",
      "Aya Finch, a lean wildlife radio technician with a shaved sidecut, round glasses, an orange field vest, cargo trousers and a coiled antenna cable",
      "Dev Harper, a soft-spoken museum conservator with freckles, close-cropped hair, a charcoal apron, pale gloves tucked at the belt and a magnifying loupe",
      "Ruth Calder, a sturdy village postmistress in her fifties with auburn curls, a burgundy cardigan, sensible skirt, weathered satchel and old silver watch",
      "Leon Pike, a wiry theatre carpenter with salt-and-pepper stubble, protective spectacles, a brown chore jacket, tool belt and a red carpenter pencil",
      "Imani Wells, a poised orchestral percussionist with long braids, a black rehearsal jacket, loose trousers, flat shoes and two felt-headed mallets",
      "Hugo Lark, a cheerful antique clock repairer with a curled moustache, thinning hair, a bottle-green waistcoat, rolled sleeves and a tiny brass gear brooch",
    ],
    subject_adventure_human: [
      "Mara Vale, a practical expedition leader in her early forties with short dark curls, an eyebrow scar, an olive field jacket, worn boots and a brass compass on a red cord",
      "Jonas Reef, a weathered salvage diver with close-cropped blond hair, a faded drysuit underlayer, reinforced knee pads and a dented copper pressure gauge",
      "Priya North, a mountain rescue navigator with a long black braid, sun-browned skin, a red insulated shell, climbing harness and a battered yellow radio",
      "Silas Quill, a lanky desert archaeologist with grey-streaked hair, wire spectacles, a sand-coloured scarf, canvas field clothes and a leather specimen tube",
      "Keira Ash, a muscular volcanic surveyor with short red hair, soot freckles, a heat-resistant grey suit, orange gloves and a compact gas sampler",
      "Owen Sable, a calm polar medic with dark skin, a frost-dusted beard, layered blue survival clothing, white snow boots and a red medical pouch",
      "Mei Orlan, an agile cave mapper with a blunt black fringe, a teal helmet, graphite coveralls, rope harness and a cluster of luminous survey markers",
      "Farah Dune, a patient wildlife tracker with hennaed hands, a loose cream headscarf, practical khaki layers and a carved wooden field notebook",
      "Cal Mercer, a broad river pilot with shaved hair, a faded orange flotation vest, rolled denim sleeves, waterproof boots and an old brass whistle",
      "Lena Crow, a wiry storm photographer with pale cropped hair, a cobalt weather jacket, reinforced trousers and a rugged camera clipped across her chest",
    ],
    subject_robot_humanoid: [
      "CIV-7, a friendly municipal service android with a cream ceramic faceplate, compact human proportions, teal joint covers and a fold-out tool panel on the left forearm",
      "Aster Unit Nine, a tall botanical caretaker robot with brushed aluminium limbs, a translucent green chest reservoir and delicate three-fingered humanlike hands",
      "Porter K4, a stocky luggage-handling automaton with rounded yellow armour, black rubber joints, broad feet and a small destination display in the chest",
      "Morrow-3, a slender archival android with a matte charcoal shell, ivory face mask, amber optical lenses and rows of tiny data cartridges along the belt",
      "Nurse HELIA, a calm medical support android with pearl-white panels, soft blue illumination, articulated humanoid hands and a compact diagnostic pack",
      "Rook Assembly 12, a rugged repair robot with rust-red plating, exposed brass pivots, one scratched optical brow and a magnetic tool strip at the hip",
      "Orchid-5, an elegant hospitality android with lilac composite panels, a smooth expressive faceplate, gold finger joints and a small tea tray folded into the back",
      "Beacon J2, a slim emergency-response android with high-visibility orange armour, white reflective bands, a blue forehead lamp and a compact rescue harness",
      "Tutor Moss, a child-height educational robot with sage-green casing, rounded humanlike limbs, a friendly pixel face and a canvas satchel full of wooden shapes",
      "Courier VELA, a fast lightweight delivery android with cobalt shell plates, long runner-like legs, silver joints and a weatherproof parcel pod across the shoulders",
    ],
    subject_fantasy_humanoid: [
      "Ilex Fernhand, a moss-skinned forest person with fern-like hair, bark-textured forearms, amber eyes, a woven reed tunic and a seed-pod pendant",
      "Bran Coalstep, a compact stone dwarf with basalt skin, a glowing ember beard, heavy leather apron, iron boots and a tiny brass furnace key",
      "Seren Tideglass, a tall amphibious envoy with pearlescent blue skin, finned ears, webbed humanoid hands, layered kelp-silk robes and a shell clasp",
      "Mallow Wick, a candle-headed humanoid with warm wax skin, a steady flame above the brow, charcoal work clothes and a copper snuffer at the belt",
      "Edda Rime, a frost giant scholar with pale crystalline skin, braided white hair, layered indigo robes, fur-lined boots and a slate tablet",
      "Pip Bramble, a small mushroom folk courier with a red-speckled cap, beige humanoid limbs, a moss waistcoat and a walnut-shell messenger bag",
      "Vesper Noon, a shadow-bodied librarian with a clear humanoid silhouette, silver eyes, a plum-coloured coat and softly drifting smoke at the cuffs",
      "Garo Sunclay, a broad terracotta guardian with carved human features, rope-bound ceramic joints, ochre cloth wraps and a blue-glazed heart tile",
      "Lumi Thread, a slender moth person with powdery cream wings folded behind a humanoid body, feathery antennae, a grey tailor's coat and gold scissors",
      "Awen Brook, a translucent river spirit with a stable human form, flowing water hair, pebble jewellery, a simple linen robe and reeds braided at the wrists",
    ],
    subject_alien_humanoid: [
      "Tala-Om, a tall four-eyed diplomat with lavender skin, a narrow humanoid frame, silver facial markings, layered white robes and a floating translation disk",
      "Kes Varo, a compact red-skinned engineer with two small brow horns, humanlike arms and legs, a graphite utility suit and luminous cyan tools",
      "Nim of Pel, a graceful long-necked explorer with jade skin, large black eyes, a sand-coloured pressure garment and a spherical sample case",
      "Orrin Sesh, a broad amphibious trader with turquoise skin, cheek gills, sturdy humanoid proportions, a copper vest and rows of glass trade tokens",
      "Veya Quen, a slender pale alien botanist with leaf-shaped ears, violet eyes, a moss-green field suit and transparent specimen tubes",
      "Hax-Rel, a sturdy insectoid humanoid with a smooth bronze carapace, two primary arms, two small folded auxiliary arms and a navy ceremonial sash",
      "Miri Vox, a soft-furred blue lunar resident with a humanlike stance, large ears, silver freckles, a quilted orange coat and magnetic snow boots",
      "Daro Kint, a tall grey nomad with a ridged crown, long humanoid hands, layered rust-coloured wraps and a black stone navigation charm",
      "Pella Nox, a compact crystalline alien with translucent rose skin, clearly humanoid limbs, a dark flexible undersuit and a glowing geometric collar",
      "Suun Ara, a gold-scaled avian humanoid with a short beak, folded feathered wings, dexterous arms, teal travelling clothes and a brass astrolabe",
    ],
    subject_historical_human: [
      "Agnes Bell, a Victorian telegraph operator with pinned chestnut hair, a high-collared navy dress, ink-stained fingers and a brass message clip",
      "Lucien March, a 1920s Parisian stage carpenter with a neat moustache, rolled linen sleeves, wide work trousers and a folding wooden rule",
      "Beatrice Cole, a 1940s code clerk with waved dark hair, round spectacles, a bottle-green cardigan, sensible skirt and a leather document pouch",
      "Edwin Pike, an Edwardian railway porter with weathered features, a burgundy waistcoat, dark uniform trousers, polished boots and a brass whistle",
      "Ada Mercer, an 1890s botanical illustrator with loosely pinned auburn hair, a cream blouse, moss-green skirt and a leather folio of pressed leaves",
      "Samuel North, a 1930s radio engineer with close-cut hair, wire spectacles, brown coveralls, heavy shoes and a compact valve tester",
      "Clara Finch, an 1810s travelling naturalist with short practical curls, a fitted blue riding coat, tan breeches, boots and a specimen case",
      "Yusuf Hale, a 1910s studio photographer with a trimmed beard, charcoal waistcoat, white shirt, dark apron and a brass light meter",
      "Mabel Thorn, a 1950s bus conductor with a curled brown bob, navy uniform, sturdy shoes and a ticket machine on a shoulder strap",
      "Arthur Reed, an 1880s lighthouse keeper with a grey beard, heavy cream knitwear, dark wool trousers, sea boots and an oil-lamp key",
    ],
    subject_scientist_human: [
      "Dr Anika Rao, a precise materials scientist with a silver-streaked braid, clear safety glasses, a pale lab coat and a labelled sample carousel without readable text",
      "Professor Elias Ward, a lanky field geologist with sandy hair, sun freckles, a rust canvas jacket, reinforced trousers and a scratched rock hammer",
      "Dr Naomi Bell, a marine biologist with close-cropped black hair, a teal drysuit underlayer, practical deck boots and a transparent specimen jar",
      "Dr Felix Moss, a compact robotics researcher with curly red hair, magnifying lenses, a charcoal utility vest and a palm-sized actuator assembly",
      "Dr Soraya Venn, an atmospheric physicist with long dark curls, a cobalt weather shell, insulated gloves and a compact silver sensor pod",
      "Dr Peter Ash, a broad forensic botanist with greying stubble, a green field shirt, tan trousers and a folded plant press",
      "Dr Hana Quill, a careful volcanologist with a blunt black fringe, an orange heat-resistant jacket, dark cargo trousers and a portable gas monitor",
      "Dr Marcus Vale, an elderly astronomer with white curls, deep brown skin, a navy cardigan, soft trousers and a small brass star chart",
      "Dr Leila Brook, an energetic acoustic engineer with a shaved sidecut, over-ear protectors around her neck, grey workwear and a calibrated microphone",
      "Dr Owen Flint, a quiet palaeontologist with a russet beard, dust-marked khaki layers, knee pads and a wrapped fossil fragment",
    ],
    subject_performer_human: [
      "Rosa Vey, a poised flamenco dancer with dark hair in a low bun, a fitted black rehearsal top, layered red skirt and worn dance shoes",
      "Theo Lark, a lean contemporary circus performer with cropped blond hair, a teal sleeveless costume, chalked hands and soft black acrobat shoes",
      "Imani Crow, a confident jazz saxophonist with long braids, a burgundy stage suit, cream shirt and an aged brass alto saxophone on a strap",
      "Niall Fern, a compact folk fiddler with curly auburn hair, a moss waistcoat, rolled sleeves, dark trousers and a weathered violin case",
      "Mei Sable, an elegant classical dancer with a neat black bun, a charcoal warm-up wrap, pale practice clothes and ribboned soft shoes",
      "Cal Dune, a broad stage magician with silver temples, a plum waistcoat, tailored black trousers and a simple deck of oversized cards",
      "Aya Reed, a lively street drummer with short blue-black curls, layered orange workwear, reinforced boots and two painted wooden sticks",
      "Hugo Pell, an elderly puppeteer with a white moustache, a brown artist's smock, corduroy trousers and one carved hand puppet",
      "Farah North, a focused theatre actor with hennaed hands, a cream rehearsal tunic, loose navy trousers and a folded script pouch without text",
      "Leon Orlan, a wiry mime performer with swept-back dark hair, subtle white stage makeup, a fitted grey costume and soft leather shoes",
    ],
    subject_mythic_humanoid: [
      "Thessa Oak, a tall antlered forest guardian with bark-brown skin, a humanoid frame, moss-lined armour and a crescent seed charm",
      "Orin Tide, a broad sea-king humanoid with blue-grey skin, finned forearms, a coral crown, layered scale cloth and a shell-handled staff",
      "Nyra Ember, a slender fire spirit with charcoal skin, glowing orange fissures, ember hair, dark woven wraps and copper ankle rings",
      "Cael Moon, a pale lunar herald with silver skin, long white hair, a simple indigo robe and a floating crescent disk behind one shoulder",
      "Mara Thorn, a sturdy horned labyrinth keeper with tawny fur on the lower legs, humanlike arms, leather workwear and a ring of iron keys",
      "Ivo Gale, a lean sky messenger with feathered forearms, a human torso, pale blue travelling clothes and a bronze wind compass",
      "Sena Glass, a crystalline oracle with a clear humanoid body, violet internal light, layered translucent veils and a dark stone pendant",
      "Bram Hollow, a compact scarecrow folk guardian with a stitched cloth face, straw at the joints, patched farm clothes and a copper bell",
      "Luma Dawn, a radiant sun priestess with warm gold skin, flame-shaped hair, cream ceremonial clothing and a round amber medallion",
      "Varr Snow, a towering yet proportionate ice warrior with frosted blue skin, white braided hair, layered fur-and-linen clothing and a slate clasp",
    ],
    subject_cybernetic_humanoid: [
      "Mina-4, a human courier with a natural face, cropped black hair, a silver left arm, graphite delivery clothing and a glowing wrist route display without text",
      "Jon Kestrel, a weathered mechanic with one amber optical implant, a reinforced right shoulder, navy coveralls and modular finger tools",
      "Asha Vale, a graceful dancer with dark skin, long braids threaded through a lightweight spinal support, plum rehearsal clothing and ceramic ankle braces",
      "Rook Harlan, a broad rescue worker with a shaved head, two powered forearm braces, orange protective workwear and a compact chest winch",
      "Eli Moss, a slim archivist with silver temple ports, round glasses, a charcoal coat and a translucent data sleeve along one forearm",
      "Nora Quen, a compact pilot with auburn curls, a cobalt pressure suit, articulated knee supports and a small circular interface at the collar",
      "Tomas Grey, an elderly gardener with a white beard, a moss-green utility coat, one precise mechanical hand and a seed dispenser at the hip",
      "Priya Forge, a muscular fabricator with a black braid, protective goggles, a rust apron and asymmetrical powered shoulder plating",
      "Sol Mercer, a calm medic with warm brown skin, a pearl-white prosthetic lower leg, teal clinical clothing and a compact diagnostic wrist module",
      "Veya Lark, a young surveyor with freckles, short silver hair, two reinforced climbing calves, a sand field suit and a chest-mounted range sensor",
    ],
  },
  CodexTurnaroundEntities: {
    item_nonhumanoid_creature: [
      "Brindle, a friendly waist-high six-legged creature with russet fur, broad moth-like ears, two ivory horns and a faded blue canvas harness",
      "a fox-sized moss grazer with four short legs, a domed fern-covered back, luminous seed eyes and tiny mushroom growths around its paws",
      "a long low glass salamander with eight translucent legs, visible blue organs, a blunt snout and a flexible crystal tail",
      "a plump floating marsh creature shaped like a pear, with two fin-like ears, mottled green skin and three dangling sensory tendrils",
      "a knee-high clockwork beetle with six brass legs, a dark red shell, exposed winding gears and a small porcelain faceplate",
      "a shaggy snow burrower with a barrel body, six black digging claws, tiny silver eyes and layered cream-and-grey fur",
      "a housecat-sized dragon with slate feathers, four legs, folded batlike wings, copper horns and a bright teal throat patch",
      "a broad river creature with smooth indigo skin, four paddle feet, whisker-like antennae and a shell-patterned back",
      "a timid cubic cave animal with velvety black skin, four stilt legs, one glowing facial slit and pale mineral plates",
      "a tiny desert pack beast with six padded feet, sandy wool, oversized cooling ears and two blue water pods on a woven harness",
    ],
    item_real_animal: [
      "a stocky Highland cow with long russet hair, curved cream horns, a yellow ear tag and mud around the lower legs",
      "a sleek black greyhound with a white chest blaze, long narrow limbs, amber eyes and a worn red leather collar",
      "a barn owl with cream facial discs, speckled tawny wings, strong pale talons and one small bronze tracking band",
      "a compact British badger with coarse grey fur, clear black-and-white facial stripes and damp soil on its claws",
      "a green iguana with a tall dorsal crest, textured scales, heavy jowls and a long banded tail",
      "a miniature Shetland pony with a dense dark mane, piebald coat, feathered fetlocks and a simple blue halter",
      "an emperor penguin with glossy black feathers, warm yellow neck patches, strong webbed feet and a small research band",
      "a red fox with thick winter fur, black legs, a white chest and a full white-tipped tail",
      "a giant African land snail with a striped brown shell, moist dark body, four extended tentacles and a small leaf stuck to the shell",
      "a scarlet macaw with vivid red plumage, blue-and-yellow wing feathers, a pale hooked beak and a plain silver leg ring",
    ],
    item_vehicle: [
      "The Calder Courier, a compact burnt-orange electric delivery van with circular headlights, cream steel wheels, black roof rails and a dented left rear door",
      "a tiny pale-blue urban street sweeper with a glazed cab, two yellow rotary brushes, narrow tyres and a striped rear water tank",
      "a rugged olive expedition motorcycle with a high front mudguard, tan seat, side panniers, protective bars and a round headlamp",
      "a cream 1960s microbus with split front windows, red lower bodywork, chrome hubcaps and a roof rack carrying one spare wheel",
      "a futuristic white single-seat lunar buggy with exposed suspension, mesh wheels, a black canopy and orange sample boxes",
      "a weathered yellow harbour tugboat with a black hull, red funnel, rubber side bumpers and a compact wheelhouse",
      "a low graphite electric sports coupe with a continuous red rear light, copper wheels and a small asymmetrical charge-port scar",
      "a practical green farm tractor with cream wheel rims, large mud-marked tyres, exposed exhaust stack and a red triangular reflector",
      "a compact silver commuter helicopter with a bubble canopy, blue tail stripe, landing skids and three main rotor blades",
      "a boxy white autonomous food cart with four small wheels, a bright green service hatch, roof sensors and a side-mounted insulated compartment",
    ],
    item_building: [
      "a narrow red-brick Victorian corner shop with a green-painted timber frontage, striped awning, slate roof and small upstairs sash windows",
      "a compact brutalist concrete library with deep square windows, a low stepped entrance and one weathered bronze sign panel without lettering",
      "a tiny off-grid cabin with charred timber cladding, a steep zinc roof, one broad picture window and a raised stone foundation",
      "a pale Art Deco cinema with rounded corners, vertical fins, teal entrance doors and a blank cream marquee",
      "a two-storey Japanese machiya townhouse with dark timber latticework, clay roof tiles, a recessed entrance and a small side garden wall",
      "a cylindrical coastal lighthouse with white masonry, a red lantern room, black gallery railings and an attached stone keeper's cottage",
      "a compact futuristic research outpost made from three linked white modules, orange airlocks, external pipes and adjustable landing feet",
      "a weathered corrugated-metal farm workshop with a sawtooth roof, wide blue sliding doors, small high windows and a brick lower course",
      "a cheerful 1950s roadside diner with stainless-steel cladding, rounded glass corners, red trim and a simple blank rooftop sign",
      "a small fantasy apothecary built into a giant hollow tree trunk, with round amber windows, a copper door, root steps and tiny hanging herb bundles",
    ],
    item_food: [
      "a thick farmhouse cheddar sandwich made with uneven seeded brown bread, mature yellow cheese, pickle at the edges, creased white paper and blue cotton string",
      "a glossy lemon tart with a fluted pastry shell, pale yellow curd, five toasted meringue peaks and a single candied peel curl",
      "a rustic bowl of tomato soup with a cream spiral, three basil leaves, black pepper and a chipped blue ceramic rim",
      "a tall stack of three blueberry pancakes with uneven edges, melting butter, dark syrup and a scattering of fresh berries",
      "a handmade vegetable dumpling with translucent pleated dough, visible green filling, one browned side and a tiny dish of chilli oil",
      "a crusty round sourdough loaf with a deep cross score, flour-dusted brown crust and one torn section revealing the open crumb",
      "a bright pistachio gelato cone with two imperfect scoops, chopped nuts, a crisp waffle cone and a small melting drip",
      "a grilled corn cob with charred kernels, lime butter, red chilli flakes and a short natural husk handle",
      "a square slice of dark chocolate cake with three moist layers, matte ganache, a few cocoa crumbs and one sharp raspberry garnish",
      "a compact bento box with rice, glazed salmon, pickled vegetables, tamagoyaki and clearly separated lacquered compartments",
    ],
    item_household_prop: [
      "a cream enamel kettle with a black wooden handle, short curved spout, red lid knob and small chips around the base",
      "a green rotary telephone with a coiled black cable, clear finger dial, cream number card and worn edges",
      "a squat amber glass bedside lamp with a pleated linen shade, brass switch and a dark green fabric cord",
      "a battered tan leather suitcase with rounded corners, brass locks, travel stickers without readable text and a repaired handle",
      "a turquoise ceramic watering can shaped with a long narrow spout, loop handle and a white mineral tide mark",
      "a compact wooden tabletop radio with cream fabric grille, two brass dials and a hairline crack in the varnish",
      "a red cast-iron mechanical kitchen scale with a round cream dial, shallow metal bowl and chipped paint on the feet",
      "a folding navy canvas deck chair with pale beechwood arms, striped seat fabric and one replaced brass hinge",
      "a round bevelled wall mirror in a dark oak frame with a small foxed patch and a simple brass hanging loop",
      "a squat mustard-yellow vacuum flask with a ribbed cup-lid, black handle, scratched base and one faded white stripe",
    ],
    item_tool: [
      "a well-used carpenter's hand plane with a beech body, dark steel blade, smooth front knob and fresh pale shavings caught at the mouth",
      "a compact cordless drill with teal housing, black rubber grips, silver chuck, scratched battery pack and one short wood bit",
      "a heavy red pipe wrench with serrated jaws, adjustment wheel, chipped paint and dark grease near the hinge",
      "a brass garden secateur with curved steel blades, green leather-wrapped handles and a simple locking clasp",
      "a small precision soldering iron with a charcoal handle, fine copper tip, braided cable and a weighted spiral stand",
      "a traditional wooden mallet with a rectangular ash head, tapered handle and compressed marks on both striking faces",
      "a folding multi-tool with brushed steel sides, red inset scales and exactly four partly visible implements",
      "a compact orange laser level with black corner bumpers, three circular windows, a magnetic base and light plaster dust",
      "a long blacksmith's tong with flat jaws, forged scale texture, circular hinge and leather wrapping around the handles",
      "a blue-handled ceramic tile cutter with parallel steel rails, a silver scoring wheel and a small bed of pale ceramic dust",
    ],
    item_machine: [
      "a compact tabletop letterpress with a cast-iron black frame, brass rollers, red flywheel and a small cream paper tray",
      "a waist-high orange seed-sorting machine with a clear hopper, vibrating metal chutes, green inspection lights and rubber feet",
      "a small brass astronomical clock with exposed gears, three concentric rings, a midnight-blue base and a single winding key",
      "a rugged portable desalination unit with a grey shell, blue hoses, two pressure gauges and a folding solar panel",
      "a coin-operated mechanical music box with a walnut cabinet, visible pinned cylinder, small brass horn and worn crank handle",
      "a futuristic desktop fabricator with a white ceramic enclosure, transparent amber door, articulated tool head and three material spools",
      "a compact green apple press with a steel screw, round wooden basket, side collection tray and dark juice stains",
      "a red emergency field generator with tubular frame, black fuel tank, silver control panel and heavy rubber vibration mounts",
      "a small automatic tea-packing machine with cream panels, exposed rollers, a paper-tag reel and a stainless output chute",
      "a laboratory centrifuge with pale grey housing, clear domed lid, six visible sample slots and a cyan status ring without text",
    ],
    item_furniture: [
      "a low mid-century lounge chair with a walnut frame, olive wool cushions, gently curved arms and a repaired seam on the seat",
      "a narrow Victorian writing desk in dark mahogany with five small drawers, green leather inset and brass keyholes",
      "a playful red moulded-plastic child's stool with three rounded legs, a circular hand hole and scuffs around the feet",
      "a tall industrial shelving unit with black steel uprights, four plywood shelves, cross bracing and one bent lower corner",
      "a compact Art Deco drinks trolley with chrome tubing, two smoked-glass shelves, black wheels and a fan-shaped handle",
      "a rustic farmhouse bench made from pale oak with pegged joints, broad splayed legs and a dark worn patch at the centre",
      "a futuristic modular sofa segment with pale grey upholstery, magnetic blue connectors and a recessed under-seat light strip",
      "a bamboo folding screen with four narrow panels, woven cane centres, brass hinges and a slightly uneven bottom edge",
      "a round café table with a white marble top, green cast-iron pedestal and a repaired gold-filled crack across one side",
      "a compact bedside cabinet painted dusty pink with one drawer, an open shelf, small brass knob and rubbed corners",
    ],
    item_artifact: [
      "an ancient bronze navigation disk with three rotating rings, green patina, tiny geometric marks and a broken leather thong",
      "a translucent blue crystal seed the size of a fist with internal branching light, six flat facets and a dark stone cradle",
      "a ceremonial ivory-coloured mask with long narrow eye openings, red thread repairs, black edge paint and a simple hanging cord",
      "a palm-sized brass mechanical bird with folded wings, ruby glass eyes, a winding key and tiny engraved feather plates",
      "a weathered stone tablet with a rounded top, shallow abstract symbols, one missing corner and traces of blue mineral pigment",
      "a silver reliquary box with a domed lid, green enamel panels, four claw feet and a tiny chain around the latch",
      "a black volcanic-glass crown with five uneven points, copper wire repairs and a soft charcoal lining",
      "a spherical wooden puzzle made from twelve interlocking dark-and-light segments with one small brass centre pin",
      "a folded star map printed on midnight-blue fabric with gold constellations, worn creases and two small magnetic corner weights",
      "a squat ceramic oracle vessel with a cream crackle glaze, three loop handles, soot-darkened base and a removable red stone stopper",
    ],
    item_watercraft: [
      "a narrow cedar rowing boat with three pale ribs, dark green gunwales, brass oarlocks and one repaired plank near the bow",
      "a compact orange rescue hovercraft with a black rubber skirt, enclosed white cabin, roof beacon and side equipment lockers",
      "a weathered blue canal narrowboat with cream window frames, a small rear cabin, brass tiller and hand-painted floral corner motifs without text",
      "a low silver hydrofoil ferry with twin hulls, dark panoramic windows, swept support struts and a cobalt passenger door",
      "a traditional red-and-black fishing skiff with a high pointed bow, timber deck, coiled rope and a small cream engine cover",
      "a rugged olive amphibious survey boat with a shallow hull, four retractable wheels, orange safety rails and a central instrument mast",
      "a tiny white autonomous harbour cleaner with twin collection arms, blue flotation pods, roof sensors and a rear debris basket",
      "a black fantasy funeral barge with a long narrow hull, silver edge trim, four low lantern mounts and a carved crescent prow",
      "a compact yellow sailing dinghy with a white centreboard, blue trim, folded mast, simple tiller and a red buoyancy bag",
      "a rounded brass-and-wood submersible pod with three circular windows, external ballast tanks, protective rails and a small top hatch",
    ],
    item_aircraft: [
      "a cream 1930s mail aeroplane with a single propeller, red wing tips, fixed landing gear and a compact enclosed cockpit",
      "a small cobalt electric air taxi with four tilting rotors, a black glass cabin, white landing skids and amber navigation lights",
      "a rugged orange bush plane with oversized tundra tyres, high wings, dark struts, a two-seat cabin and a repaired left wing tip",
      "a slender silver sailplane with a clear bubble canopy, extremely long wings, one black tail stripe and a single retractable wheel",
      "a compact yellow agricultural drone with six rotors, a translucent central tank, folding spray arms and sturdy black landing legs",
      "a red twin-boom firefighting aircraft with a high wing, broad water tank, two propellers and reinforced landing gear",
      "a tiny white scientific balloon gondola with a cubic frame, silver instruments, orange padding and four suspension cables",
      "a fantasy courier glider shaped from dark wood and cream canvas, with swept wings, brass hinges and a narrow open cockpit",
      "a matte-black reconnaissance drone with a flying-wing silhouette, two recessed fans, a glass sensor dome and pale grey access panels",
      "a cheerful teal gyrocopter with an open two-seat cockpit, yellow tail fins, three rotor blades and a compact rear propeller",
    ],
    item_nonhumanoid_robot: [
      "a waist-high warehouse robot with a low yellow body, four mecanum wheels, a telescoping shelf lift and a blue status ring",
      "a dog-sized inspection robot with four graphite legs, a white sensor head, orange joint covers and a coiled sampling arm",
      "a compact orchard robot with six narrow wheels, a green chassis, two padded picking arms and a transparent fruit crate",
      "a round domestic floor robot with cream casing, three retractable brushes, a small amber display and a fabric carry loop",
      "a knee-high library robot with a dark wood-effect shell, two quiet tracks, a lifting book cradle and a brass-coloured sensor mast",
      "a rugged red pipe-crawling robot with six magnetic feet, a flexible segmented body, inspection lights and a cable spool",
      "a floating white medical supply drone with a circular body, four enclosed fans, a red insulated drawer and soft blue lights",
      "a small brass clockwork spider automaton with eight articulated legs, a glass gear chamber and one winding key",
      "a low black agricultural rover with wide rubber tracks, a silver soil probe, folding solar wings and a green sample hopper",
      "a playful turquoise educational robot shaped like a squat cube, with four rounded wheels, two folding manipulators and a pixel face",
    ],
    item_musical_instrument: [
      "a weathered honey-brown acoustic guitar with a dark pickguard, repaired side crack, brass tuning pegs and a woven shoulder strap",
      "a compact red accordion with cream keys, patterned bellows, worn leather hand straps and brass corner protectors",
      "a tall concert harp with a walnut frame, gold mechanism, forty-seven visible strings and a small carved leaf at the crown",
      "a matte-black modular synthesizer with two stacked panels, coloured patch cables, silver knobs and wooden side cheeks",
      "a deep blue cello with a warm varnished neck, ebony fittings, one pale repaired seam and an extended steel endpin",
      "a circular bronze handpan with nine hammered tone fields, blue heat colouring and a dark woven carrying ring",
      "a compact bamboo transverse flute with seven finger holes, dark binding thread and a small jade end cap",
      "a brass sousaphone with a broad forward bell, white shoulder tubing, three valves and light performance tarnish",
      "a fantasy crystal keyboard with twelve translucent keys, a dark stone base, soft internal violet light and no readable markings",
      "a small oak hurdy-gurdy with a carved wheel cover, four drone strings, brass crank and a faded red fabric strap",
    ],
    item_clothing_accessory: [
      "a pair of sturdy brown expedition boots with reinforced toes, red laces, mud in the tread and a repaired left heel",
      "a wide-brimmed moss-green felt hat with a dark leather band, one brass pin and rain-softened edges",
      "a compact charcoal messenger bag with a broad canvas strap, copper buckles, three outer pockets and one blue repair patch",
      "a pair of pearl-white articulated gauntlets with dark flexible joints, small gold fasteners and padded inner cuffs",
      "a long burgundy wool scarf with narrow cream stripes, hand-knotted fringe and one careful darned repair",
      "a circular brass-and-glass brooch shaped like a compass rose, with a blue enamel centre and a simple rear pin",
      "a practical orange climbing harness with black webbing, silver buckles, padded leg loops and two blue gear loops",
      "a dark indigo ceremonial mask with narrow eye openings, silver edge stitching, a smooth inner lining and two tying cords",
      "a pair of round protective goggles with amber lenses, a black rubber frame, adjustable strap and fine scratches",
      "a compact cream hard-shell backpack with teal straps, a dark lower panel, side clips and a small circular lamp",
    ],
    item_container: [
      "a squat blue ceramic jar with a cork lid, two loop handles, white mineral marks and a narrow repaired crack",
      "a rugged orange equipment case with black corner guards, two silver latches, pressure valve and fitted foam interior",
      "a tall green glass apothecary bottle with a ground stopper, broad shoulders, bubbles in the glass and no label",
      "a woven willow picnic basket with a split lid, tan leather straps, cream cloth lining and one darker replacement weave",
      "a cylindrical brushed-steel sample canister with three locking bands, blue rubber seals and a recessed carry handle",
      "a small dark oak treasure box with brass corners, curved lid, red felt interior and a simple keyhole",
      "a translucent amber food-storage tub with a cream snap lid, rounded corners and light scuffing around the base",
      "a fantasy stone reliquary shaped like a low hexagon, with copper hinges, a violet crystal latch and soft moss in the seams",
      "a tall cream enamel flour bin with a red lid, twin side handles, chipped lower edge and no lettering",
      "a flexible charcoal water bladder with reinforced seams, orange cap, two attachment loops and a coiled drinking hose",
    ],
    item_plant: [
      "a mature bonsai pine with a twisted dark trunk, layered green needles, exposed roots and a shallow blue ceramic pot",
      "a tall monstera plant with eight broad split leaves, pale aerial roots and a weathered terracotta planter",
      "a compact desert cactus cluster with five ribbed green stems, golden spines, two pink flowers and a chipped cream pot",
      "a dense red-leaf Japanese maple sapling with a slender grey trunk, fine branches and a black nursery container",
      "a trailing string-of-pearls succulent with long green strands, tiny round leaves and a hanging copper bowl",
      "a broad fantasy lantern plant with dark teal leaves, three translucent amber seed pods and tangled silver roots",
      "a practical kitchen herb planter containing rosemary, thyme and sage in a long green enamel trough with soil marks",
      "a tall white orchid with five open flowers, glossy leaves, visible support clips and a pale stoneware pot",
      "a weathered coastal shrub with wind-bent branches, small silver-green leaves, exposed roots and a low stone planter",
      "a carnivorous pitcher plant with six striped red-and-green traps, glossy leaves and a dark moss-covered pot",
    ],
    item_landmark_structure: [
      "a weathered stone village well with a circular wall, timber roof, iron crank, wooden bucket and moss around the base",
      "a compact red-painted pedestrian bridge with a shallow arch, timber deck, black railings and stone end supports",
      "a tall freestanding clock tower with pale masonry, a copper roof, four blank clock faces and an arched base opening",
      "a small brutalist bus shelter with folded concrete walls, a timber bench, one amber light and no signage",
      "a ceremonial stone gateway formed from two square pillars and a broad lintel, with bronze bands and worn steps",
      "a circular Victorian bandstand with green iron columns, cream roof, raised timber floor and decorative railings",
      "a futuristic public charging canopy with a white curved roof, six slim supports, blue light strips and a central service column",
      "a rustic wooden watchtower with four braced legs, an enclosed top cabin, ladder stair and a small red flag without symbols",
      "a fantasy roadside shrine made from dark stone, a copper peaked roof, three candle niches and a shallow offering bowl",
      "a compact stone fountain with a broad lower basin, central bronze fish, four water spouts and mineral staining",
    ],
    item_toy: [
      "a hand-made wooden pull-along fox with orange paint, black wheels, cream ears and a red cotton cord",
      "a small tinplate wind-up robot with silver bodywork, blue arms, red feet, a square face and a brass key",
      "a soft knitted green dragon with cream horns, uneven button eyes, stubby wings and a repaired tail seam",
      "a compact wooden dollhouse with a blue roof, cream walls, four open rooms and simple unpainted furniture",
      "a vintage red pedal car with cream wheels, a silver grille, black seat and light scuffs around the body",
      "a set of twelve interlocking geometric blocks in muted wood colours, arranged as one stable abstract tower",
      "a clockwork brass carousel toy with four tiny horses, a red canopy, blue base and a side winding handle",
      "a plush grey rabbit with long ears, embroidered black eyes, a mustard waistcoat and a carefully darned left paw",
      "a futuristic magnetic construction toy made from silver rods and coloured spheres, assembled into a small bridge",
      "a paper theatre toy with a folding red proscenium, three layered scenery cards and two flat puppet figures without text",
    ],
    item_scifi_device: [
      "a palm-sized white translation device with a black glass centre, three amber lights, a silver edge and no readable display",
      "a rugged graphite environmental scanner with a folding handle, circular sensor head, orange bumpers and a blue status strip",
      "a compact silver gravity compass with three floating rings, a dark stone base and a single cyan reference point",
      "a cylindrical cream medical regenerator with a transparent chamber, teal seals, two padded grips and small service panels",
      "a low black holographic projector with a triangular base, three glass emitters, copper vents and soft violet light",
      "a portable orange matter sampler with a clear specimen drum, folding legs, a silver probe and black control paddles",
      "a slim cobalt memory archive with stacked translucent wafers, a white protective frame and one red physical release lever",
      "a fantasy-science weather engine with a brass spherical cage, four ceramic coils, a walnut base and tiny internal lightning",
      "a compact white drone-control console with two folding grips, a dark central screen, yellow safety edging and no text",
      "a silver emergency beacon with a broad magnetic foot, telescoping antenna, red protective cage and a pulsing amber core",
    ],
  },
  CodexCharacterTraits: {
    character_palette: [
      "a restrained palette of charcoal, rust orange and bone white",
      "deep forest green with worn tan and small brass accents",
      "cool slate blue, soft cream and one vivid coral identifier",
      "dusty burgundy, warm grey and faded mustard details",
      "ink black, pale silver and controlled cyan illumination",
      "earthy umber, moss green and muted copper highlights",
      "soft lilac, graphite and pearl-white trim",
      "sand, terracotta and a narrow band of cobalt blue",
      "weathered navy, oatmeal and dark red accents",
      "jade green, ivory and subtle antique-gold details",
    ],
    character_silhouette: [
      "a compact practical silhouette with a low centre of gravity",
      "a tall narrow silhouette with long clean limb lines",
      "a broad triangular silhouette with strong shoulders and grounded feet",
      "a softly rounded approachable silhouette with layered shapes",
      "an agile forward-leaning silhouette with close-fitting equipment",
      "a formal upright silhouette with balanced bilateral details",
      "a sturdy rectangular silhouette with visible working joints",
      "an elegant tapered silhouette with one asymmetrical shoulder detail",
      "a small energetic silhouette with oversized hands and boots",
      "a weathered traveller's silhouette built from uneven layered clothing",
    ],
    character_wardrobe: [
      "layered practical workwear with visible pockets and reinforced seams",
      "a clean formal uniform softened by one well-used personal garment",
      "weatherproof expedition clothing with a short jacket and secure harness points",
      "simple hand-made natural-fibre clothing with careful visible repairs",
      "a fitted technical undersuit beneath a few hard protective panels",
      "loose artistic studio clothing with rolled sleeves and pigment marks",
      "ceremonial clothing with restrained geometric trim and no loose trailing fabric",
      "warm quilted outerwear with knitted cuffs and sturdy boots",
      "minimal monochrome clothing shaped by belts, straps and one bold collar",
      "vintage utility clothing combining a waistcoat, durable trousers and practical shoes",
    ],
    character_condition: [
      "freshly prepared but not pristine, with tiny believable signs of use",
      "well maintained after years of service, with polished contact points",
      "lightly rain-damp with darker fabric edges and a few water droplets",
      "dusty from recent travel, especially around boots, hems and lower panels",
      "carefully repaired in two visible places using contrasting thread or plates",
      "clean and presentation-ready with only subtle handling marks",
      "sun-faded on upward-facing surfaces while protected areas retain colour",
      "workshop-worn with small scratches, grease traces and softened edges",
      "cold-weather frosted around exposed edges without obscuring identity",
      "heirloom condition, preserved but showing fine cracks and gentle patina",
    ],
    character_accessory: [
      "one compact field notebook secured to the left hip",
      "a distinctive circular pendant on a short practical cord",
      "a small weathered satchel worn close across the torso",
      "a pair of protective goggles resting above the brow",
      "one clearly designed hand tool clipped safely at the belt",
      "a narrow identification band around the right upper arm",
      "a compact radio or communicator mounted high on the chest",
      "a folded cloth map in a transparent waterproof pouch",
      "one asymmetrical shoulder guard bearing a simple geometric emblem",
      "a small specimen container attached to a secure cross-body strap",
    ],
    character_personality: [
      "visually calm, observant and quietly competent",
      "warmly eccentric with one playful but functional detail",
      "disciplined and formal without appearing aggressive",
      "curious and approachable, with open posture and softened shapes",
      "resourceful and heavily practical, with nothing purely decorative",
      "scholarly and meticulous, expressed through orderly equipment",
      "weathered but optimistic, with confident relaxed bearing",
      "reserved and mysterious while remaining physically plausible",
      "inventive and slightly improvised, with clever visible repairs",
      "ceremonial and dignified, using symmetry and restrained ornament",
    ],
    character_head_detail: [
      "a swept-back crown detail formed from hair, feathers, fins or casing as appropriate",
      "one compact asymmetrical headpiece secured above the right temple",
      "a clean centre-parted head silhouette with two controlled side details",
      "a short practical crest or cropped hair shape that leaves the face unobstructed",
      "a rounded protective cap integrated naturally with the character's materials",
      "two small balanced horn, antenna or ornament forms kept close to the skull",
      "a soft hood or cowl folded behind the head so all facial views remain clear",
      "one narrow braid, cable or decorative strand falling behind the left shoulder",
      "a layered crown silhouette with a clearly readable front and side profile",
      "a distinctive but restrained forehead detail centred above the brow line",
    ],
    character_face_marking: [
      "one narrow diagonal identity mark across the right cheek or faceplate",
      "three tiny dots arranged beneath the left eye in a material-appropriate finish",
      "a subtle contrasting band across the brow without obscuring the eyes",
      "one small crescent-shaped mark beside the left temple",
      "a restrained line of freckles, rivets or scales across the upper cheeks",
      "a pale vertical mark centred from lower lip to chin or equivalent faceplate area",
      "one clearly visible repaired notch at the outer right brow",
      "a pair of fine symmetrical markings following the cheekbone lines",
      "a small circular identity spot just below the left eye",
      "a clean unmarked face with identity carried by natural surface variation",
    ],
    character_hand_detail: [
      "bare or exposed hands with clearly readable fingers, joints and material texture",
      "short practical gloves with contrasting reinforced palms",
      "one gloved hand and one exposed hand, explained by the character's work",
      "slim articulated finger guards that preserve a humanlike hand silhouette",
      "dark wrist wraps ending before the knuckles",
      "pale protective gloves with one coloured identification cuff",
      "visible hand repairs, calluses or joint wear appropriate to the character",
      "compact tool interfaces integrated into one fingertip without changing hand count",
      "simple rings or joint bands limited to two fingers",
      "clean undecorated hands designed for maximum pose readability",
    ],
    character_footwear: [
      "sturdy ankle boots with broad soles and a contrasting heel repair",
      "lightweight fitted shoes with a clean tapered silhouette",
      "heavy weatherproof boots with visible tread and reinforced toes",
      "soft wrapped footwear secured with two practical cross-straps",
      "integrated humanoid feet with dark contact pads instead of separate shoes",
      "formal low shoes with restrained metal or enamel edge details",
      "knee-high field boots with scuffed lower panels and simple closures",
      "compact climbing boots with protected ankles and one coloured lace loop",
      "traditional flat shoes made from layered natural material",
      "asymmetrical but balanced footwear with one visibly replaced left sole",
    ],
    character_back_detail: [
      "a slim practical back panel or pack that does not hide the body silhouette",
      "two short shoulder straps meeting at one central rear clasp",
      "a narrow vertical spine detail with three repeated segments",
      "one folded fabric panel secured high between the shoulders",
      "a compact tool roll attached horizontally at the lower back",
      "a small circular rear emblem placed between the shoulder blades",
      "clean uncluttered back construction with seams or joints clearly visible",
      "one asymmetrical cable, braid or strap running from right shoulder to left hip",
      "a shallow protective plate following the upper-back contour",
      "a neatly rolled weather layer fastened across the top of a small pack",
    ],
    character_signature_motif: [
      "a repeated concentric-circle motif used in exactly two small locations",
      "one restrained diagonal stripe that reappears on an accessory",
      "a small crescent identity motif echoed at collar and wrist",
      "three aligned square details used as a consistent personal signature",
      "a subtle leaf or feather form repeated in trim and one clasp",
      "one cobalt triangular accent repeated on opposite sides of the body",
      "a narrow copper line tracing two major construction seams",
      "a simple black-and-cream checker detail limited to one small band",
      "a paired amber dot motif used on the chest and one ankle",
      "a clean design with no emblem, relying on silhouette and material contrast",
    ],
  },
  CodexItemTraits: {
    item_palette: [
      "charcoal, burnt orange and warm cream",
      "forest green, weathered tan and antique brass",
      "cobalt blue, pale grey and one coral-red accent",
      "dusty burgundy, blackened steel and muted gold",
      "sage green, ivory and dark walnut brown",
      "terracotta, sand and a small turquoise detail",
      "deep navy, soft white and oxidised copper",
      "mustard yellow, graphite and pale blue",
      "plum, silver and restrained cyan illumination",
      "natural brown, moss green and chalky red",
    ],
    item_material: [
      "a physically plausible mixture of painted steel, rubber and textured glass",
      "honest natural materials combining timber, canvas, leather and brass fasteners",
      "matte ceramic shells joined by dark flexible seals and small metal fittings",
      "weathered stone paired with oxidised copper and a few clear glass elements",
      "woven natural fibre, glazed ceramic and carefully tied cotton cord",
      "brushed aluminium, translucent polymer and high-wear rubber contact surfaces",
      "cast iron, enamel paint and pale unfinished wood handles",
      "layered organic surfaces with fur, shell, horn or leaf-like structures only where appropriate",
      "recycled composite panels with visible bolts, repair plates and fabric straps",
      "fine dark wood with silver hardware, coloured enamel and one mineral inset",
    ],
    item_condition: [
      "newly made but handled enough to avoid showroom perfection",
      "well maintained after long service, with polished edges and light scuffs",
      "rain-damp with realistic droplets, darker porous materials and clean reflections",
      "dusty around the lower surfaces and recesses after recent travel",
      "carefully repaired with one obvious but elegant replacement component",
      "sun-faded across upper faces while sheltered areas retain deeper colour",
      "workshop-worn with tiny scratches, grease traces and softened grips",
      "archaeological but structurally complete, with stable patina and minor chips",
      "cold-weather frosted on exposed edges without hiding construction details",
      "freshly cleaned while retaining believable age, seams and manufacturing variation",
    ],
    item_signature_detail: [
      "one small circular emblem repeated exactly twice without readable text",
      "a single asymmetrical cobalt repair plate fixed with four brass fasteners",
      "one red cotton cord tied around a practical anchor point",
      "a distinctive triangular vent, opening or marking on the left side",
      "three narrow cream stripes grouped together on one major surface",
      "a tiny amber indicator light housed inside a protective metal ring",
      "one visibly hand-made handle wrapped in dark green leather",
      "a repeating shallow wave motif used sparingly around the edges",
      "one contrasting replacement wheel, foot, hinge or corner protector",
      "a clear identity feature based on a concentric circle geometry",
    ],
    item_design_language: [
      "compact municipal utility design with rounded safe corners",
      "mid-century industrial design with simple honest mechanisms",
      "quiet contemporary craft with restrained hand-made irregularity",
      "rugged expedition equipment designed for repair in the field",
      "optimistic near-future design with clean modules and visible service panels",
      "Victorian scientific-instrument design without excessive decoration",
      "friendly educational design using clear shapes and tactile controls",
      "minimal Japanese-influenced design with balanced material transitions",
      "rural workshop construction made from available robust components",
      "ceremonial fantasy design grounded in believable weight and assembly",
    ],
    item_scale: [
      "small enough to hold securely in two hands",
      "roughly knee-high beside an average adult, though no person appears",
      "roughly waist-high beside an average adult, though no person appears",
      "approximately the size of a large domestic dog, though no animal appears",
      "compact enough to fit on a sturdy tabletop",
      "human-scale furniture or equipment with believable ergonomic dimensions",
      "small vehicle scale with clearly readable doors, wheels or access points",
      "full building scale while remaining completely visible in every overall view",
      "large machine scale with construction details that explain its weight",
      "miniature collectible scale with crisp materials rather than toy-like simplification",
    ],
    item_universal_asymmetry: [
      "one subtle left-right asymmetry appropriate to its anatomy or construction",
      "a slightly larger feature on the right side balanced by a smaller left detail",
      "one carefully repaired area confined to the lower-left portion",
      "an otherwise symmetrical design with a single off-centre functional element",
      "one edge, limb, opening or fitting showing greater wear than its counterpart",
      "a small secondary attachment placed only on the right rear quarter",
      "one naturally irregular contour preserved consistently in every view",
      "a deliberate diagonal relationship between two existing identity features",
      "one colour accent appearing on only a single appropriate component or body area",
      "near-perfect symmetry, with variation limited to believable wear and manufacture",
    ],
    item_universal_identity_feature: [
      "one unmistakable circular identity feature integrated into an appropriate surface or body region",
      "three small repeated marks following an existing structural or anatomical line",
      "one contrasting repaired seam, scar or joint that remains visible across relevant views",
      "a distinctive triangular opening, marking or plate used without altering function",
      "one clearly recognisable handle, horn, stem, crest or raised form appropriate to the subject",
      "a narrow band of contrasting colour wrapped around one logical section",
      "one small amber-coloured focal detail protected by the surrounding form",
      "a paired set of pale edge details placed on opposite sides",
      "one dark inset area creating a recognisable identity without readable text",
      "a clean silhouette-led identity with no added emblem or decorative symbol",
    ],
    item_universal_surface_story: [
      "subtle contact wear concentrated only where handling, movement or weather would cause it",
      "fine surface variation that preserves the base subject's correct material or biology",
      "one small area recently cleaned, contrasting with gently aged surrounding surfaces",
      "light rain or condensation behaviour appropriate to each existing surface",
      "soft dust accumulation limited to upward-facing recesses and lower edges",
      "careful maintenance visible through polished contact points and protected joints",
      "minor sun fading on exposed upper areas while sheltered colour remains richer",
      "one old repair integrated honestly without changing the subject's class or scale",
      "freshly made surfaces with slight hand-built or manufacturing variation",
      "neutral well-documented condition with no artificial damage added",
    ],
    item_universal_function_cue: [
      "one visible feature clearly explaining how the subject moves, opens, grows, supports or is handled",
      "a readable access, attachment or articulation point appropriate to the selected subject",
      "one protected contact area showing where weight or force is naturally carried",
      "a simple repeated structure revealing how the subject was assembled or developed",
      "one practical closure, joint, stem, grip or service point suited to the base design",
      "a clearly readable underside feature that explains balance or support",
      "one restrained functional detail at the rear without inventing a new purpose",
      "an honest transition between two existing materials or biological structures",
      "a visible maintenance, feeding, storage or growth feature only when appropriate",
      "no extra mechanism added; function remains legible through the original form alone",
    ],
    item_universal_edge_detail: [
      "softly worn outer edges with sharper protected recesses",
      "a narrow contrasting rim following one major existing boundary",
      "small chips, fraying or surface irregularity appropriate to the base material",
      "one reinforced corner, tip or extremity using a compatible material",
      "clean rounded transitions at all high-contact outer edges",
      "a fine dark line separating two major existing surfaces or body regions",
      "slight thickness variation along one hand-made or naturally grown edge",
      "a polished highlight limited to the most exposed ridge or contour",
      "one carefully repaired edge section that remains structurally plausible",
      "plain unaccented edges that let the main silhouette carry the identity",
    ],
    item_universal_consistency_rule: [
      "preserve the exact same asymmetries, wear and small details in every panel",
      "keep all repeated components identical in count, spacing and orientation across views",
      "maintain one coherent scale and material response throughout the complete sheet",
      "show every attachment and marking in its correct corresponding position from each angle",
      "retain the base subject's original anatomy or construction without category mixing",
      "keep colours stable under the neutral lighting with no panel-to-panel redesign",
      "preserve all repairs, scars, seams and surface variation consistently across views",
      "maintain physically plausible weight, support and balance from every direction",
      "do not add text, extra components or alternate versions in any panel",
      "treat the selected description as a locked production design, not a loose variation theme",
    ],
  },
};

function validateLibrary(lib) {
  const errors = [];
  const categorySet = new Set(lib.categories);
  for (const cat of lib.listCats) if (!categorySet.has(cat)) errors.push(`List category missing from categories: ${cat}`);
  const seen = new Set();
  for (const tag of lib.tags) {
    const key = String(tag.name).toLowerCase();
    if (seen.has(key)) errors.push(`Duplicate tag name: ${tag.name}`);
    seen.add(key);
    if (tag.kind === "list") {
      const lines = tag.text.split(/\r?\n/).map((x) => x.trim()).filter(Boolean);
      if (lines.length !== 10) errors.push(`${tag.name} has ${lines.length} choices, expected 10`);
      if (!lib.listCats.includes(tag.cat)) errors.push(`${tag.name} is a list but category ${tag.cat} is not list-side`);
    }
  }
  if (errors.length) throw new Error(errors.join("\n"));
}

async function main() {
  const response = await fetch(settingsUrl);
  if (!response.ok) throw new Error(`Could not read live Tag Library: HTTP ${response.status}`);
  const stored = await response.json();
  const library = typeof stored === "string" ? JSON.parse(stored) : stored;
  if (!library || !Array.isArray(library.categories) || !Array.isArray(library.tags)) throw new Error("Live Tag Library has an unexpected shape");

  fs.mkdirSync(backupDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = path.join(backupDir, `pixaroma-tag-library-before-expanded-entity-mix-${stamp}.json`);
  fs.writeFileSync(backupPath, `${JSON.stringify(library, null, 2)}\n`, "utf8");

  const newCategories = Object.keys(lists);
  library.categories = library.categories.filter((cat) => !newCategories.includes(cat));
  library.categories.push(...newCategories);
  library.listCats = (library.listCats || []).filter((cat) => !newCategories.includes(cat));
  library.listCats.push(...newCategories);
  const newNames = new Set(Object.values(lists).flatMap((group) => Object.keys(group)).map((name) => name.toLowerCase()));
  library.tags = library.tags.filter((tag) => !newNames.has(String(tag.name).toLowerCase()));

  for (const [cat, tags] of Object.entries(lists)) {
    for (const [name, choices] of Object.entries(tags)) {
      if (choices.length !== 10) throw new Error(`${name} source has ${choices.length} choices, expected 10`);
      library.tags.unshift({ name, cat, text: choices.join("\n"), kind: "list" });
    }
  }
  library.version = 1;
  library.catModes = library.catModes && typeof library.catModes === "object" ? library.catModes : {};
  validateLibrary(library);

  const payload = JSON.stringify(library, null, 2);
  const post = await fetch(settingsUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!post.ok) throw new Error(`Could not write live Tag Library: HTTP ${post.status}`);

  fs.writeFileSync(exportPath, `${payload}\n`, "utf8");
  const confirmed = await (await fetch(settingsUrl)).json();
  const live = typeof confirmed === "string" ? JSON.parse(confirmed) : confirmed;
  validateLibrary(live);
  const installed = live.tags.filter((tag) => newNames.has(String(tag.name).toLowerCase()));
  console.log(JSON.stringify({
    settingsFile: settingFile,
    backupPath,
    exportPath,
    categoriesAdded: newCategories,
    listTagsInstalled: installed.length,
    choicesInstalled: installed.reduce((sum, tag) => sum + tag.text.split(/\r?\n/).filter((x) => x.trim()).length, 0),
    totalCategories: live.categories.length,
    totalTags: live.tags.length,
  }, null, 2));
}

main().catch((error) => {
  console.error(error.stack || error.message || String(error));
  process.exitCode = 1;
});
